"""empty message

Revision ID: 890d859277e9
Revises: 29e3a2217903
Create Date: 2020-06-27 09:55:40.837502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '890d859277e9'
down_revision = '29e3a2217903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
