"""empty message

Revision ID: 97036b4ee8b3
Revises: 283f964ad42f
Create Date: 2020-06-27 09:25:29.304315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97036b4ee8b3'
down_revision = '283f964ad42f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'website')
    op.drop_column('Venue', 'seeking_talent')
    op.drop_column('Venue', 'seeking_description')
    # ### end Alembic commands ###
